config/routes.rb
Simvla::Application.routes.draw do

  get "landing/index"

  get "join/index"
  post "join/create"

  get "dashboard/index"

  resources :messages
  resources :roles
  resources :members

  resources :posts do
    collection do
      post :add_image
    end
    resources :user
    collection do
      post :add_like
    end
    member do
      post :preview
    end
  end


  devise_for :users do
    resources :posts
  end

  devise_scope :user do
    delete "sign_out", :to => "devise/sessions#destroy"
  end

  constraints(Subdomain) do
    match '/' => 'posts#show'
  end

  match "beta" => "members#index"
  root :to => 'landing#index'
end

app/views/layouts/shared/_footer.html.erb
		<section id="events" class="alpha omega clearfix bottom-margin" >
			
<div class="backtop" style="text-align: center;">
<a href="https://www.iubenda.com/privacy-policy/400778" class="iubenda-nostyle no-brand iub-legal-only iubenda-embed" title="Privacy Policy" style="color: black;font-family: proximanova-extrabld, sans-serif;font-size: 12px;text-transform: uppercase;background: #eee;padding: 10px;border-radius: 3px;-webkit-border-radius: 3px;-moz-border-radius: 3px; padding-top: 12px;">Privacy Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src = "https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; w.addEventListener ? w.addEventListener("load", loader, false) : w.attachEvent("onload", loader);})(window, document);</script></div>	
		</div><!-- container -->
		

	</section><!-- footer -->

app/views/layouts/shared/_form_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation" style="width: 100%;text-align: center;margin-top: 20px;font-family: proxima-nova, sans-serif;font-size: 30px;">
    errori
  </div>
<% end %>

app/views/layouts/shared/_form_error_e.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
      <%= obj.errors.count %>
      <% if obj.errors.count==1%>
        <%=t(:error)%>
      <% else%>
        <%=t(:errors)%>
      <%=t(:form_error)%>
      <% end %>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/shared/_head.html.erb
<head id="top-page">

    <!-- Basic Page Needs
  ================================================== -->
    <meta charset="utf-8">
    <title>Simvla Network</title>
    <meta name="description" content="Blogging Network for Designers and Developers.">
    <meta name="Keywords" content="blogging network, simvla, independet publishing platform, blogging community, svbtle" />

    <!-- Mobile Specific Metas
  ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
  ================================================== -->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->


    <!-- Javascript
    ================================================== -->

<script type="text/javascript" src="//use.typekit.net/tar0tza.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

<script>
$(document).ready(function() {
   $('a[href=#top]').click(function(){
        $('html, body').animate({scrollTop:0}, 'slow');
        return false;
    });
});
</script>

<script type="text/javascript">
  var GoSquared = {};
  GoSquared.acct = "GSN-152153-T";
  (function(w){
    function gs(){
      w._gstc_lt = +new Date;
      var d = document, g = d.createElement("script");
      g.type = "text/javascript";
      g.src = "//d1l6p2sc9645hc.cloudfront.net/tracker.js";
      var s = d.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(g, s);
    }
    w.addEventListener ?
      w.addEventListener("load", gs, false) :
      w.attachEvent("onload", gs);
  })(window);
</script>

    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31228077-8']);
  _gaq.push(['_setDomainName', '.simvla.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>

app/views/layouts/shared/_header.html.erb
<section id="intro-wrap" data-winht="0" >
  <section id="nav-wrap">
    <ul id="nav" class="clearfix">			
      <ul class="button-group radius">
        <li>
          <%= link_to "Login", new_user_session_path, :class => "button radius hide-for-small"%>
        </li>
        <li>
          <%= link_to "Apply", new_message_path, :class => "button radius hide-for-small"%>
        </li>
        <li><a href="mailto:hello@simvla.com" class="button radius hide-for-small">Contact</a></li>
        <li><a href="http://twitter.com/simvlanetwork" class="button radius hide-for-small" style="color: skyblue;">Follow on Twitter</a></li>
        <li>
          <%= link_to "Ntwrk Feed", member_path(User.where(:email => "admin@simvla.com").first, :format => :rss), :class =>  "button radius hide-for-small", :style =>  "color: salmon;" %>
          
          
        </li>
      </ul>
      <%= link_to "Simvla", root_path, :id => :logo%>
    </ul><!-- nav --> 
  </section><!-- nav-wrap -->		 

  <div id="intro" class="clearfix"></div><!--/.intro -->
</section><!-- Section #1 / Intro-wrap -->

app/views/layouts/shared/_menu_admin.html.erb
<div class="sidebar"><!-- Sidebar -->
    <div class="navContiner">
    <a href="https://simvla.com/"><h1 style="font-family: Conv_ProximaNova-Black;background: black;color: white;padding-top: 30px;margin-top: -1px;text-align: center;font-size: 70px;padding-bottom: 24px;">S</h1></a>
        <ul id="nav"><!-- Navigation -->
          <li>
          <%= link_to dashboard_index_path do %>
          <i class="ss-icon" style="font-size: 50px; color: #7d8295;">dashboard</i>
          <% end %>
          </li>
            <li>
                <a href="#"><i class="ss-icon" style="font-size: 50px; color: #7d8295;">users</i> </a>
                <!-- Flyout menu -->
                <ul class="flyout">
                    <li><span></span></li>
                    <li>
                    <%= link_to members_path do %>
                      &mdash; Active Members
                    <% end %>
                    </li>
                    <li>
                    <%= link_to new_member_path do %>
                      &mdash; Add New Members
                    <% end %>
                    </li>
                </ul>
            </li>
            <li>
              <%= link_to '/sign_out', :method => :delete do %>
                <i class="ss-icon" style="font-size: 50px; color: #7d8295;">lock</i>
              <% end %>
            </li>

    </div>
    <div class="flyoutBg"></div>
</div>
</div>

app/views/layouts/shared/_overlay.erb
 <div id="osx-modal-content">
        <div id="osx-modal-title">Getting Started with Simvla</div>
        <div class="close"><a href="#" class="simplemodal-close">x</a></div>
        <div id="osx-modal-data">
            <a href="http://en.wikipedia.org/wiki/Textile_(markup_language)#Textile_syntax_examples" style="font-size: 25px;"><i class="icon-list-alt" style="font-size: 22px;color: black;margin-right: 16px;"></i>Markup Language</a>
            <p>Textile is a lightweight markup language originally developed by Dean Allen and billed as a "humane web text generator". Textile converts its marked-up text input to valid, well-formed XHTML and also inserts character entity references for apostrophes, opening and closing single and double quotation marks, ellipses and em dashes.</p>
            <a href="http://alexgorbatchev.com/SyntaxHighlighter/manual/demo/" style="font-size: 25px;"><i class="icon-list-alt" style="font-size: 21px;color: black;margin-right: 16px;"></i>Syntax Highlighter</a>
            <p>SyntaxHighlighter is a fully functional self-contained code syntax highlighter. To get an idea of what SyntaxHighlighter is capable of, have a look at the <a href="http://alexgorbatchev.com/SyntaxHighlighter/manual/demo/">demo page.</a></p>
            <a href="#" style="font-size: 25px;"><i class="icon-list-alt" style="font-size: 21px;color: black;margin-right: 16px;"></i>Drag & Drop Upload</a>
            <p>Drop an image into the body of your post where you want it to appear, and it will automatically upload. Easy as that!</a></p>
            <a href="#" style="font-size: 25px;"><i class="icon-list-alt" style="font-size: 21px;color: black;margin-right: 16px;"></i>Post's External Source</a>
            <p>Click the External Source button in the editor and place a link to an external source for that post, a link icon will compare next to the post title.</a></p>

        </div>
 </div>