config/routes.rb
Simvla::Application.routes.draw do

  get "landing/index"

  get "join/index"
  post "join/create"

  get "dashboard/index"

  resources :messages
  resources :roles
  resources :members

  resources :posts do
    collection do
      post :add_image
    end
    resources :user
    collection do
      post :add_like
    end
    member do
      post :preview
    end
  end


  devise_for :users do
    resources :posts
  end

  devise_scope :user do
    delete "sign_out", :to => "devise/sessions#destroy"
  end

  constraints(Subdomain) do
    match '/' => 'posts#show'
  end

  match "beta" => "members#index"
  root :to => 'landing#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  paginates_per 10
  validates :title, :presence => true, :length => {:minimum => 1, :maximum => 100}
  #validates :body, :presence => true
  validates :user_id, :presence => true
  has_many :posts_images

  belongs_to :user

  scope :visible, lambda{|user|
    if user.role?(:admin)
      where(:is_public => true).order("updated_at desc")
    else
      where(:is_public => true, :user_id => user.id).order("updated_at desc")
    end
  }

  scope :draft, lambda{|user|
    if user.role?(:admin)
      where(:is_public => false).order("updated_at desc")
    else
      where(:is_public => false, :user_id => user.id).order("updated_at desc")
    end
  }

  def get_rc
    self.body.blank? ? "" : RedCloth.new(self.body).to_html
  end

  def world_count
    self.body.blank? ? 0 : self.body.split(" ").size
  end

  def reading_time
    rt = world_count/2.80/60
    return rt==0 ? 1 : rt.to_i
  end

  def add_like
    update_attribute(:likes, likes.to_i+1)
  end

  def self.likes_count
    t = 0
    Post.all.each{|p| t+=p.likes.to_i}
    return t
  end

  def self.words_count
    t = 0
    Post.all.each{|p| t+=p.world_count}
    return t
  end

  def self.reading_times
    t = 0
    Post.all.each{|p| t+=p.reading_time}
    return t
  end

  def to_param
    "#{id}-#{self.title.parameterize}"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :add_like]
  load_and_authorize_resource :class => false, :except => [:index, :show, :add_like]
  # GET /posts
  # GET /posts.json
  def index
    @posts_draft = Post.select('id,title').draft(current_user)
    @posts_visible = Post.select('id,created_at,title,likes,body').visible(current_user)

    respond_to do |format|
      if current_user.present?
        format.html{ render :index, layout: 'backend' }
      else
        redirect_to root_path
        #format.html{ render :template => "posts/fe/index"}
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user = User.find_by_subdomain!(request.subdomain)
    if params[:id].present?
      @post = Post.find(params[:id])
    else
      @posts = Post.visible(@user).page params[:page]
    end

    respond_to do |format|
      #if current_user.present?
      #  format.html # show.html.erb
      #else
        if params[:id].present?
          format.html{ render :template => "posts/fe/show_post", layout: 'blog'}
        else
          format.html{ render :template => "posts/fe/show", layout: 'blog'}
      #  end
      end
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @post.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    respond_to do |format|
        format.html { render :edit, notice: 'Post was successfully created.', layout: "backend" }
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    
    if params[:preview].to_s == "true"
      @user = current_user
      @post = Post.new(params[:post])
      @post.created_at = DateTime.now
      respond_to do |format|
        format.html { render :template => "posts/fe/show_post", layout: "blog" }
      end
    else
      respond_to do |format|
        if @post.update_attributes(params[:post])
          format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        else
          format.html { render action: "edit" }
        end
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_path }
    end
  end

  #add_like_post GET    /posts/:id/add_like(.:format)           posts#add_like
  def add_like
    post = Post.find(params[:id])
    post.add_like
    render nothing: true
  end
  
  def preview
    @user = current_user
    @post = Post.find(params[:id])
    respond_to do |format|
        format.html { render :template => "posts/fe/show_post", layout: "blog" }
    end
  end

   def add_image
     @pic = PicturesPost.new
     tmp_file =  FilelessIO.new(Base64.decode64(params[:image]))
     tmp_file.original_filename = "#{Time.now.to_i.to_s}.#{params[:format_image].to_s}"
     @pic.image = tmp_file
     @pic.save
     render json: {filename: @pic.image.url.gsub(/\.s3\.amazonaws\.com/,'')}
   end
end

 class FilelessIO < StringIO
     attr_accessor :original_filename
 end

app/views/posts/_form.html.erb
<% if @post.new_record? %>
  <div id="new_record" data-value="true"></div>
<% else %>
  <div id="new_record" data-value="false"></div>
<% end %>
<%= form_for(@post) do |f| %>
  <%= f.hidden_field :user_id %>
  <%= hidden_field_tag :preview, "false", :id => "preview" %>
  <div class="new_post_visible"  style="display:none">
    <%= f.check_box :is_public %>
  </div>
    <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="wrap">
            <p>
                <%= f.text_field :title, :class => "text", :placeholder => "Title Here", :size => "60", :tabindex => "1" %>
            </p>

            <p>
              <%=image_tag 'load.gif', :style=>'position:absolute;display:none',id: 'loader'%>
              <%= f.text_area :body, :placeholder => "Write post here", :size => "60", :tabindex => "2" %>
            </p>
    </div>

    <div class="buttons">
        <div class="double">
            <input type="radio" class="RadioClass" name="post_status" value="draft" checked="<%= !@post.is_public ? 'checked' : '' %>" id="">
            <a href="#" class="button <%= !@post.is_public ? 'checked' : '' %>" data-id="<%=@post.id%>" data-action="false">Idea</a>

            <input type="radio" class="RadioClass" name="post_status" value="publish" checked="<%= @post.is_public ? 'checked' : '' %>">
            <a href="#" class="button <%= @post.is_public ? 'checked' : '' %>" data-id="<%=@post.id%>" data-action="true">Public</a>
        </div>
         <%=link_to "External Source",'#', :style => "background: #F76;",:class=>'button show_hide black'%>
         <%=link_to "Preview", "#", :id => "preview1", :data => {:href => preview_post_path(@post)}, :class=>'button show_hide black'%>
         <%=link_to "Save", "#", :id => "save", :class=>'button show_hide black'%>
         <%=link_to "Delete", @post,confirm: 'Are you sure?',method: :delete,:class=>"button remove black"%>
         <%=link_to posts_path,:class=>'button black' do %>
           <i class="icon-list-ul" style="font-size: 20px; color: white; margin-top: 5px;"></i>
         <%end%>
         </div>
        <div class="slidingDiv" style="display: block;">
        <%= f.text_field :link, :class => "text", :placeholder => "Where do we go?", :size => "60", :tabindex => "1" %>
    </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function() {
        $notice = $('p.wps-notice');
        if($notice.length) {
            $notice.fadeOut(2000);
        }
    });
    
    $('#preview1').live('click', function(event){
        event.preventDefault();
        $("#preview").val('true')
        $('.edit_post').attr("target","_blank");
        $('.edit_post').submit();
    });
    $('#save').live('click', function(event){
        event.preventDefault();
        $("#preview").val('false')
        $('.edit_post').attr("target","");
        $('.edit_post').submit();
    });
</script>

<div id="p_post" style="display:none;">
<%= form_for(@post, :remote => true) do |f| %>
  <%= f.text_field :id %>
  <%= f.check_box :is_public, :class => "p_post_visible" %>
  <%=f.submit "sss", :class => "button"%>
<% end %>
</div>

app/views/posts/_navigation.erb
<%=link_to posts_path,:class=>'button logout' do %>
    <i class="icon-list-ul" style="font-size: 20px; color: black; margin-left: 0px;"></i>
<%end%>

<%= link_to edit_member_path(current_user),:class=>'button logout' do %>
  <i class="icon-wrench" style="font-size: 20px; color: black; margin-left: 0px;"></i>
<%end%>
<%= link_to '/sign_out',  method: :delete, :class => "button logout" do  %>
  <i class="icon-signout" style="font-size: 20px; color: black; margin-left: 0px;"></i>
<%end%>

<div id="welcome-back">
    Welcome Back •
</div>
<div id="member-name">
     <%=link_to_if  current_user.external_link, current_user.username, current_user.external_link %></a>
</div>
</div>
<div id="part-of">
    <a href="http://simvla.com">Simvla</a>
</div>
<div id="how-to">
    <h2>
        <a href="" class="button how-to osx demo"><i class="icon-beaker" style="font-size: 15px;color: white;margin-right: 6px;"></i>Get Started</a>
    </h2>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="wrap">
<div class="module">
    <div class="ideas">
        <h2>
            <%= link_to "New Post", new_post_path, :style => "background: #5AB1F3;",:class=> 'button new-entry' %>
            Drafts
        </h2>

        <%= form_for Post.new, :style => "width:103%;",:class => "form-idea" do |f| %>
        <span style="display:none">
            <%= f.text_field :user_id, :value => current_user.id %>
            <%= f.check_box :is_public %>
        </span>
        <%= f.text_field :title, :style => "font-size: 20px; margin-left: 19px;",:class => "start_typing", :placeholder => "Type something then hit Enter..."%>
        <div class="hidden-submit"><input type="submit" tabindex="-1"/></div>
        <% end %>

        <% @posts_draft.each do |post| %>
        <p>
        <%= link_to post.title, edit_post_path(post) %>
        </p>
        <% end %>
    </div><!-- .ideas -->
</div><!-- .ideas -->


<div class="published module">
    <h2>Live Posts</h2>
    <% @posts_visible.each do |post| %>
    <p>
        <span class="word-count">
          <%= post.world_count %> Words • <%=post.likes%>
          <i class="icon-thumbs-up" style="font-size: 14px; color: white; margin-left: 0px;"></i>
          – Posted <%=post.created_at.strftime("%B %d, %Y")%>
        </span>
     </p>
       <p>
          <%= link_to post.title, edit_post_path(post)  %>
      </p>
    <% end %>
</div>
</div>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>

<p>
  <b>User:</b>
  <%= @post.user_id %>
</p>

<p>
  <b>Is public:</b>
  <%= @post.is_public %>
</p>

<p>
  <b>Likes:</b>
  <%= @post.likes %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>